# Generated by Django 3.0.3 on 2020-03-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200315_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='previuos_post',
            new_name='previous_post',
        ),
    ]
